# Generated by Django 5.1.4 on 2025-01-12 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ctegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='produt nomini kiriting')),
                ('description', models.TextField(blank=True, null=True, verbose_name='product haqida malumot kiriting')),
                ('price', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='narxi')),
                ('quantity', models.SmallIntegerField(default=100, verbose_name='Ombordagi soni')),
                ('weight', models.DecimalField(decimal_places=2, default=10, max_digits=4, verbose_name='ogirligi')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Productlar',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='hillarni kiriting')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ctegory')),
            ],
            options={
                'verbose_name': 'tur',
                'verbose_name_plural': 'turlar',
            },
        ),
    ]
