# Generated by Django 5.1.4 on 2025-01-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_created_at_productimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctegory',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
